image: alpine:latest

before_script:
  - apk add --update --no-cache openssh sshpass

actualizar:
  stage: deploy
  script:
  - sshpass -p $PASSWORD ssh -o StrictHostKeyChecking=no -p $PORT $USERNAME@$HOST 'cd frontend && git pull origin main && docker compose --file ./docker-compose.yml up --build -d'

  only:
  - main
